---
- hosts: tomcat-docker
  become: yes
  tasks:
   - name: Add Docker Repository
     get_url:
       url: https://download.docker.com/linux/centos/docker-ce.repo
       dest: /etc/yum.repos.d/

   #- name: Install Containerd for docker-ce dependency 
     #shell: dnf install --nobest docker-ce -y
     #dnf:
     #name: https://download.docker.com/linux/centos/7/x86_64/edge/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm
     #state: present

   - name: Install Docker-ce
     shell: dnf install --nobest docker-ce -y
     #dnf:
     #name: docker-ce
     #state: present

   - name: enable docker service is started and enabled
     systemd:
       name: docker
       enabled: yes
       state: started


